export const LINKS = {
    DISCORD: 'https://discord.gg/4d7QWUK',
    GITHUB: 'https://github.com/mpunkenhofer/lisc',
    PAYPAL: 'https://paypal.me/litags',
}

export const ICONS = {
    'Albion': '0',
    'Hibernia': '1',
    'Midgard': '2',
    'Animist': 'A',
    'Armsman': 'B',
    'Bard': 'C',
    'Berserker': 'D',
    'Blademaster': 'E',
    'Bonedancer': 'F',
    'Cabalist': 'G',
    'Champion': 'H',
    'Cleric': 'I',
    'Druid': 'J',
    'Eldritch': 'K',
    'Enchanter': 'L',
    'Friar': 'M',
    'Healer': 'N',
    'Hero': 'O',
    'Hunter': 'P',
    'Infiltrator': 'Q',
    'Mentalist': 'R',
    'Mercenary': 'S',
    'Minstrel': 'T',
    'Necromancer': 'U',
    'Nightshade': 'V',
    'Paladin': 'W',
    'Ranger': 'X',
    'Reaver': 'Y',
    'Runemaster': 'Z',
    'Savage': 'a',
    'Scout': 'b',
    'Shadowblade': 'c',
    'Shaman': 'd',
    'Skald': 'e',
    'Sorcerer': 'f',
    'Spiritmaster': 'g',
    'Thane': 'h',
    'Theurgist': 'i',
    'Valewalker': 'j',
    'Warden': 'k',
    'Warrior': 'l',
    'Wizard': 'm'
}